export default function generateShareText(data, filename) {
  const lines = [
    `ContractIQ Analysis: ${filename}`,
    `Document Type: ${data.document_type}`,
    `Risk Level: ${data.overall_risk_score}`,
    '',
    'SUMMARY',
    data.executive_summary,
    '',
    `PARTIES: ${data.parties.map(p => `${p.name} (${p.role})`).join(', ')}`,
    '',
    `KEY FINDINGS:`,
    `- ${data.key_terms.length} key terms identified`,
    `- ${data.obligations.length} obligations tracked`,
    `- ${data.risk_flags.length} risk flags (${data.risk_flags.filter(r => r.severity === 'high').length} high severity)`,
    `- ${data.key_dates.length} key dates`,
    `- ${data.financial_terms.length} financial terms`,
    '',
    `Risk Assessment: ${data.risk_score_explanation}`,
    '',
    '— Generated by ContractIQ',
  ];
  return lines.join('\n');
}
